image:
  file: .gitpod.Dockerfile
tasks:
  - init: npm install
    command: npm start
ports:
  # preview
  - port: 8000
    onOpen: open-preview
  # live-reload: Broken because of bad automatic configuration of live-reload plugin
  # See: https://github.com/schickling/gulp-webserver/pull/126
  - port: 35729
    onOpen: ignore
